%读入附件表格1_3_1作为训练集
XLS=readmatrix("1_3_1");     
Input=XLS(:,2:13);
Output=XLS(:,14:17);
%得到的结果储存在net中
%下面这一大段代码为系统自动生成，在程序最后有输出预测和赋值的代码

% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by Neural Fitting app
% Created 02-Apr-2022 23:44:09
%
% This script assumes these variables are defined:
%
%   Input - input data.
%   Output - target data.

x = Input';
t = Output';

% Choose a Training Function
% For a list of all training functions type: help nntrain
% 'trainlm' is usually fastest.
% 'trainbr' takes longer but may be better for challenging problems.
% 'trainscg' uses less memory. Suitable in low memory situations.
trainFcn = 'trainbr';  % Bayesian Regularization backpropagation.

% Create a Fitting Network
hiddenLayerSize = 10;
net = fitnet(hiddenLayerSize,trainFcn);

% Setup Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 70/100;
net.divideParam.valRatio = 15/100;
net.divideParam.testRatio = 15/100;

% Train the Network
[net,tr] = train(net,x,t);

% Test the Network
y = net(x);
e = gsubtract(t,y);
performance = perform(net,t,y)

% View the Network
view(net)

% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, ploterrhist(e)
%figure, plotregression(t,y)
%figure, plotfit(net,x,t)

%读入附件表格1_3_2_2作为输出
XLS=readmatrix("1_3_2_2.xlsx");     
Input_2=XLS(:,2:13)';%输入要作为列矩阵
Output_2=sim(net,Input_2);%预测输出

%下面填入数据（Output_2）到表格二'1_3_2_2.xlsx'中
writematrix(Output_2','1_3_2_2.xlsx','Range','N2:Q31');